# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eITEHqpjWCF3qYMZNwhK04lJ1Wcp3378
"""

## Projeto calculadora

nome_usuario = 0

print('Olá , iremos ser sua calculadora pessoal!')
nome_usuario = input('Digite seu nome: \n')


print('Olá,', nome_usuario , '!Agora vamos fazer algumas contas!\n')

## Parte da Calculadora

num1= int(input('Digite seu primeiro numero:\n'))
num2= int(input('Digite seu segundo numero:\n'))

print('Você digitou''[',num1,']''e''[',num2,']''.Agora vamos decidir qual opção matemática você deseja realizar!\n')

print('Escolha qual operação matemática você deseja:\n')
operacao = input('[ 1 ] = [ SOMA ] \n[ 2 ] = [ SUBTRAÇÃO ] \n[ 3 ] = [ MULTIPLICAÇÃO ]\n[ 4 ] = [ DIVISÃO ]\n')


# Fase Final

if operacao == "1":
  resultado = num1 + num2
  print('Você escolheu SOMAR e o resultado é:',resultado,'!')
  print('Obrigado por utilizar nossa calculadora!')

elif operacao == '2':
  resultado = num1 - num2
  print('Você escolheu SUBTRAÇÃO e o resultado é:',resultado,'!')
  print('Obrigado por utilizar nossa calculadora!')

elif operacao == '3':
  resultado = num1 * num2
  print('Você escolheu MULTIPLICAÇÃO e o resultado é:',resultado,'!')
  print('Obrigado por utilizar nossa calculadora!')

elif operacao == '4':
  resultado = num1 / num2
  print('Você escolheu DIVISÃO e o resultado é:',resultado,'!')
  print('Obrigado por utilizar nossa calculadora!')

else:
 print('Você não digitou uma opção válida, tente novamente!')